services:
  react-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:80"  # expone NGINX en el puerto 3000 de tu máquina
    networks:
      - spring-network

networks:
  spring-network:
    external: true  # si ya la creaste con el backend
